/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_centos_tensorflowandroid_TensorFlowClassifier */

#ifndef _Included_com_example_centos_tensorflowandroid_TensorFlowClassifier
#define _Included_com_example_centos_tensorflowandroid_TensorFlowClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_centos_tensorflowandroid_TensorFlowClassifier
 * Method:    initializeTensorFlow
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;IIILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_centos_tensorflowandroid_TensorFlowClassifier_initializeTensorFlow
  (JNIEnv *, jobject, jobject, jstring, jint, jint, jint, jstring, jstring);

/*
 * Class:     com_example_centos_tensorflowandroid_TensorFlowClassifier
 * Method:    classifyImageBmp
 * Signature: (Landroid/graphics/Bitmap;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_centos_tensorflowandroid_TensorFlowClassifier_classifyImageBmp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_centos_tensorflowandroid_TensorFlowClassifier
 * Method:    classifyImageRgb
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_centos_tensorflowandroid_TensorFlowClassifier_classifyImageRgb
  (JNIEnv *, jobject, jintArray, jint, jint);


/*
 * Class:     com_example_centos_tensorflowandroid_TensorFlowClassifier
 * Method:    classifyImageYUV
 * Signature: ([B[B[BIIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_centos_tensorflowandroid_TensorFlowClassifier_classifyImageYUV
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
